[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }
axum = { version = "0.8.1", features = ["macros"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = { version = "1.0.140" }

http = "1.0.0"
http-body = "1.0.0"
http-body-util = "0.1.0"

